# Generated by Django 5.2.5 on 2025-09-06 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_address_line1_profile_line1_profile_user_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health'), ('heart_disease', 'Heart Disease'), ('covid_19', 'Covid19'), ('immunization', 'Immunization'), ('fitness', 'Fitness')], max_length=50)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
